export const mainCatalogDataFront = {
  'avto-moto': {
    name: 'Авто-мото',
    slug: 'avto-moto',
    path: 'avto-moto',
    subcategories: [
      { name: 'Запчасти', slug: 'zapchasti-dlia-avto-i-spetstekhniki', path: 'avto-moto/zapchasti-dlia-avto-i-spetstekhniki' },
      { name: 'Шины', slug: 'shiny', path: 'avto-moto/shiny-i-diski/shiny', inline: true, hasSeparator: true },
      { name: 'Диски', slug: 'diski', path: 'avto-moto/shiny-i-diski/diski', inline: true, hasSeparator: true },
      { name: 'Колпаки', slug: 'kolpaki', path: 'avto-moto/shiny-i-diski/kolpaki', inline: true, hasSeparator: false },
      { name: 'Аккумуляторы', slug: 'akkumuliatory', path: 'avto-moto/akkumuliatory' },
      { name: 'Принадлежности', slug: 'avto-prinadlezhnosti', path: 'avto-moto/avto-prinadlezhnosti' },
      { name: 'Автохимия и ГСМ', slug: 'avtokhimiia-i-gsm', path: 'avto-moto/avtokhimiia-i-gsm' },
      { name: '...', slug: 'avto-moto', path: 'avto-moto', isDots: true },
    ],
  },
  'kompiutery-i-tsifrovaia-tekhnika': {
    name: 'Компьютеры и цифровая техника',
    slug: 'kompiutery-i-tsifrovaia-tekhnika',
    path: 'kompiutery-i-tsifrovaia-tekhnika',
    subcategories: [
      { name: 'Фото и видеокамеры', slug: 'foto-i-videokamery', path: 'kompiutery-i-tsifrovaia-tekhnika/foto-i-videokamery' },
      { name: 'Телефоны', slug: 'telefony-umnye-chasy', path: 'kompiutery-i-tsifrovaia-tekhnika/telefony-umnye-chasy' },
      { name: 'Умные часы и фитнес-браслеты', slug: 'telefony-umnye-chasy', path: 'kompiutery-i-tsifrovaia-tekhnika/telefony-umnye-chasy' },
      { name: 'Ноутбуки', slug: 'noutbuki', path: 'kompiutery-i-tsifrovaia-tekhnika/pk-noutbuki-planshety/noutbuki', inline: true, hasSeparator: true },
      { name: 'Планшеты', slug: 'planshety', path: 'kompiutery-i-tsifrovaia-tekhnika/pk-noutbuki-planshety/planshety', inline: true, hasSeparator: false },
      { name: 'Персональные компьютеры', slug: 'personalnye-kompiutery', path: 'kompiutery-i-tsifrovaia-tekhnika/pk-noutbuki-planshety/personalnye-kompiutery' },
      { name: 'Периферия', slug: 'periferiia-monitory-klaviatury-i-td', path: 'periferiia-monitory-klaviatury-i-td', inline: true, hasSeparator: true },
      { name: 'Комплектующие', slug: 'komplektuiushchie', path: 'kompiutery-i-tsifrovaia-tekhnika/pk-noutbuki-planshety/komplektuiushchie', inline: true, hasSeparator: false },
      { name: 'Игровые приставки и консоли', slug: 'igrovye-pristavki-i-konsoli', path: 'kompiutery-i-tsifrovaia-tekhnika/igrovye-pristavki-i-konsoli' },
      { name: '...', slug: 'kompiutery-i-tsifrovaia-tekhnika', path: 'kompiutery-i-tsifrovaia-tekhnika', isDots: true },
    ],
  },
  'stroitelstvo-remont-stroi-prom-materialy': {
    name: 'Строительство, ремонт, материалы',
    slug: 'stroitelstvo-remont-stroi-prom-materialy',
    path: 'stroitelstvo-remont-stroi-prom-materialy',
    subcategories: [
      { name: 'Сантехника', slug: 'santekhnika', path: 'stroitelstvo-remont-stroi-prom-materialy/santekhnika', inline: true, hasSeparator: true },
      { name: 'Электрика', slug: 'elektrika', path: 'stroitelstvo-remont-stroi-prom-materialy/elektrika', inline: true, hasSeparator: false },
      { name: 'Плитка / Кафель', slug: 'plitka-kafel-i-oblitsovochnyi-kamen', path: 'stroitelstvo-remont-stroi-prom-materialy/plitka-kafel-i-oblitsovochnyi-kamen' },
      { name: 'Двери', slug: 'dveri-furnitura-zamki-i-t-d', path: 'stroitelstvo-remont-stroi-prom-materialy/dveri-furnitura-zamki-i-t-d', inline: true, hasSeparator: true },
      { name: 'Окна', slug: 'okna', path: 'stroitelstvo-remont-stroi-prom-materialy/okna', inline: true, hasSeparator: false },
      { name: 'Пиломатериалы', slug: '', path: '' },
      { name: 'Древесные плиты', slug: '', path: '' },
      { name: 'Металлопрокат', slug: '', path: '' },
      { name: 'Цемент и строительные смеси', slug: '', path: '' },
      { name: 'Лакокрасочные материалы', slug: '', path: '' },
      { name: '...', slug: 'stroitelstvo-remont-stroi-prom-materialy', path: 'stroitelstvo-remont-stroi-prom-materialy', isDots: true },
    ],
  },
  'instrumenty-i-oborudovanie': {
    name: 'Инструменты и оборудование',
    slug: 'instrumenty-i-oborudovanie',
    path: 'instrumenty-i-oborudovanie',
    subcategories: [
      { name: 'Общего назначения', slug: 'obshchego-naznacheniia', path: 'instrumenty-i-oborudovanie/obshchego-naznacheniia' },
      { name: 'Строительное', slug: 'stroitelnoe', path: 'instrumenty-i-oborudovanie/stroitelnoe' },
      { name: 'Для авторемонта', slug: 'dlia-avtoremonta', path: 'instrumenty-i-oborudovanie/dlia-avtoremonta' },
      { name: 'Промышленное и коммерческое', slug: 'promyshlennoe-i-kommercheskoe', path: 'instrumenty-i-oborudovanie/promyshlennoe-i-kommercheskoe' },
    ],
  },
  'bytovaia-tekhnika': {
    name: 'Бытовая техника',
    slug: 'bytovaia-tekhnika',
    path: 'bytovaia-tekhnika',
    subcategories: [
      { name: 'Холодильники и морозильники', slug: 'kholodilniki-i-morozilnye-kamery', path: 'bytovaia-tekhnika/kholodilniki-i-morozilnye-kamery' },
      {
        name: 'Плиты, духовые шкафы и варочные панели',
        slug: 'gazovye-i-elektro-plity-dukhovye-shkafy-i-varochnye-paneli',
        path: 'bytovaia-tekhnika/gazovye-i-elektro-plity-dukhovye-shkafy-i-varochnye-paneli',
      },
      { name: 'Стиральные машины', slug: 'stiralnye-mashiny', path: 'bytovaia-tekhnika/stiralnye-mashiny' },
      { name: 'Кондиционеры', slug: 'konditsionery', path: 'bytovaia-tekhnika/konditsionery' },
      { name: 'Водонагреватели', slug: '', path: '' },
      { name: '...', slug: 'appliances', path: 'appliances', isDots: true },
    ],
  },
  'mebel-i-interer': {
    name: 'Мебель и интерьер',
    slug: 'mebel-i-interer',
    path: 'mebel-i-interer',
    subcategories: [
      { name: 'Диваны', slug: 'divany', path: 'mebel-i-interer/divany', inline: true, hasSeparator: true },
      { name: 'Кровати', slug: 'krovati', path: 'mebel-i-interer/krovati', inline: true, hasSeparator: true },
      { name: 'Матрасы', slug: 'matrasy', path: 'mebel-i-interer/matrasy', inline: true, hasSeparator: false },
      { name: 'Кухни', slug: 'kukhni', path: 'mebel-i-interer/kukhni' },
      { name: 'Столы', slug: 'stoly', path: 'mebel-i-interer/stoly' },
      { name: 'Стулья, табуретки, кресла', slug: 'stulia-taburetki-kresla', path: 'mebel-i-interer/stulia-taburetki-kresla' },
      { name: 'Шкафы', slug: 'shkafy', path: 'mebel-i-interer/shkafy', inline: true, hasSeparator: true },
      { name: 'Комоды и тумбы', slug: '', path: '', inline: true, hasSeparator: false },
      { name: 'Текстиль для дома', slug: '', path: '' },
      { name: 'Шторы и жалюзи', slug: '', path: '' },
      { name: '...', slug: 'mebel-i-interer', path: 'mebel-i-interer', isDots: true },
    ],
  },
  'vodnaia-tekhnika': {
    name: 'Водная техника',
    slug: 'vodnaia-tekhnika',
    path: 'vodnaia-tekhnika',
  },
  'sport-turizm-okhota': {
    name: 'Спорт, туризм, охота',
    slug: 'sport-turizm-okhota',
    path: 'sport-turizm-okhota',
  },
  'tovary-dlia-dachi-sada-i-ogoroda': {
    name: 'Товары для дачи, сада и огорда',
    slug: 'tovary-dlia-dachi-sada-i-ogoroda',
    path: 'tovary-dlia-dachi-sada-i-ogoroda',
  },
  'tovary-dlia-zhivotnykh': {
    name: 'Товары для животных',
    slug: 'tovary-dlia-zhivotnykh',
    path: 'tovary-dlia-zhivotnykh',
  },
  'odezhda-obuv-i-aksessuary': {
    name: 'Одежда, обувь. аксуссуары',
    slug: 'odezhda-obuv-i-aksessuary',
    path: 'odezhda-obuv-i-aksessuary',
    subcategories: [
      { name: 'Женская одежда', slug: 'zhenskaia-odezhda', path: 'odezhda-obuv-i-aksessuary/zhenskaia-odezhda', inline: true, hasSeparator: true },
      { name: 'Женская обувь', slug: '', path: '', inline: true, hasSeparator: false },
      { name: 'Мужская одежда', slug: 'muzhskaia-odezhda', path: 'odezhda-obuv-i-aksessuary/muzhskaia-odezhda', inline: true, hasSeparator: true },
      { name: 'Мужская обувь', slug: '', path: '', inline: true, hasSeparator: false },
      { name: 'Детская одежда', slug: 'detskaia-odezhda-cross', path: 'odezhda-obuv-i-aksessuary/detskaia-odezhda-cross', inline: true, hasSeparator: true },
      { name: 'Детская обувь', slug: 'detskaia-obuv', path: 'odezhda-obuv-i-aksessuary/detskaia-obuv', inline: true, hasSeparator: false },
      { name: '\u00A0', slug: 'emptyLine', path: 'emptyLine' },
      { name: 'Аксессуары и бижутерия', slug: 'aksessuary-i-bizhuteriia', path: 'odezhda-obuv-i-aksessuary/aksessuary-i-bizhuteriia' },
      { name: 'Спецодежда', slug: 'spetsodezhda', path: 'odezhda-obuv-i-aksessuary/spetsodezhda' },
    ],
  },
  'posuda-i-kukhonnye-prinadlezhnosti': {
    name: 'Посуда и кухонные принадлежности',
    slug: 'posuda-i-kukhonnye-prinadlezhnosti',
    path: 'posuda-i-kukhonnye-prinadlezhnosti',
    subcategories: [
      { name: 'Посуда', slug: 'posuda', path: 'posuda-i-kukhonnye-prinadlezhnosti/posuda' },
      { name: 'Столовые приборы', slug: 'stolovye-pribory', path: 'posuda-i-kukhonnye-prinadlezhnosti/stolovye-pribory' },
      { name: 'Кухонный инвентарь и аксессуары', slug: 'kukhonnyi-inventar-i-aksessuary', path: 'posuda-i-kukhonnye-prinadlezhnosti/kukhonnyi-inventar-i-aksessuary' },
    ],
  },
  'tkani-i-shveinaia-furnitura': {
    name: 'Ткани и швейная фурнитура',
    slug: 'tkani-i-shveinaia-furnitura',
    path: 'tkani-i-shveinaia-furnitura',
  },
  'kantstovary-i-knigi': {
    name: 'Канцтовары',
    slug: 'kantstovary-i-knigi',
    path: 'kantstovary-i-knigi',
  },
  'produkty-i-napitki': {
    name: 'Продукты и напитки',
    slug: 'produkty-i-napitki',
    path: 'produkty-i-napitki',
  },
  'tara-i-upakovka': {
    name: 'Тара и упаковка',
    slug: 'tara-i-upakovka',
    path: 'tara-i-upakovka',
  },
  krasota: {
    name: 'Красота',
    slug: 'krasota',
    path: 'krasota',
  },
  zdorove: {
    name: 'Здоровье',
    slug: 'zdorove',
    path: 'zdorove',
  },
  'podarki-suveniry-tsvety': {
    name: 'Подарки, сувениры, цветы',
    slug: 'podarki-suveniry-tsvety',
    path: 'podarki-suveniry-tsvety',
  },
  'deti-i-materinstvo': {
    name: 'Товары для детей',
    slug: 'deti-i-materinstvo',
    path: 'deti-i-materinstvo',
    subcategories: [
      { name: 'Коляски и переноски', slug: 'koliaski-i-perenoski', path: 'deti-i-materinstvo/koliaski-i-perenoski' },
      { name: 'Питание и кормление', slug: 'pitanie-i-kormlenie', path: 'deti-i-materinstvo/pitanie-i-kormlenie' },
      { name: 'Гигиена и уход', slug: 'gigiena-i-ukhod', path: 'deti-i-materinstvo/gigiena-i-ukhod' },
      { name: 'Игрушки и игры', slug: 'igrushki-i-igry', path: 'deti-i-materinstvo/igrushki-i-igry' },
      { name: 'Детские спортивные товары и активный отдых', slug: 'detskie-sportivnye-tovary-i-aktivnyi-otdykh', path: 'deti-i-materinstvo/detskie-sportivnye-tovary-i-aktivnyi-otdykh' },
      { name: 'Школа', slug: 'shkola', path: 'deti-i-materinstvo/shkola' },
    ],
  },
};
