export const mainCatalogDataFront = {
  'auto-moto': {
    name: 'Авто-мото',
    slug: 'auto-moto',
    full_path: 'auto-moto',
    categories: [
      { name: 'Запчасти', slug: 'parts', full_path: 'auto-moto/parts' },
      { name: 'Шины — ', slug: '', full_path: '' },
      { name: 'Диски — ', slug: '', full_path: '' },
      { name: 'Колпаки', slug: '', full_path: '' },
      { name: 'Аккумуляторы', slug: '', full_path: '' },
      { name: 'Принадлежности', slug: '', full_path: '' },
      { name: 'Автохимия и ГСМ', slug: '', full_path: '' },
      { name: '...', slug: '', full_path: '' },
    ],
  },
  'computers-tech': {
    name: 'Компьютеры и цифровая техника',
    slug: 'computers-tech',
    full_path: 'computers-tech',
    categories: [
      { name: 'Фото и видеокамеры', slug: 'photo-video', full_path: '' },
      { name: 'Телефоны', slug: '', full_path: '' },
      { name: 'Умные часы и фитнес-браслеты', slug: '', full_path: '' },
      { name: 'Ноутбуки — ', slug: '', full_path: '' },
      { name: 'Планшеты', slug: '', full_path: '' },
      { name: 'Персональные компьютеры', slug: '', full_path: '' },
      { name: 'Периферия — ', slug: '', full_path: '' },
      { name: 'Комплектующие', slug: '', full_path: '' },
      { name: 'Игровые приставки и консоли', slug: 'gaming-consoles', full_path: 'computers-tech/gaming-consoles' },
      { name: '...', slug: '', full_path: '' },
    ],
  },
  construction: {
    name: 'Строительство, ремонт, материалы',
    slug: 'construction',
    full_path: 'construction',
    categories: [
      { name: 'Сантехника — ', slug: 'plumbing', full_path: 'construction/plumbing' },
      { name: 'Электрика', slug: 'electrics', full_path: 'construction/electrics' },
      { name: 'Плитка / Кафель', slug: '', full_path: '' },
      { name: 'Двери — ', slug: '', full_path: '' },
      { name: 'Окна', slug: 'windows', full_path: 'construction/windows' },
      { name: 'Пиломатериалы', slug: 'lumber', full_path: 'construction/lumber' },
      { name: 'Древесные плиты', slug: 'wood-boards', full_path: 'construction/wood-boards' },
      { name: 'Металлопрокат', slug: 'metal-roll', full_path: 'construction/metal-roll' },
      { name: 'Цемент и строительные смеси', slug: 'cement-mixes', full_path: 'construction/cement-mixes' },
      { name: 'Лакокрасочные материалы', slug: 'paints', full_path: 'construction/paints' },
      { name: '...', slug: '', full_path: '' },
    ],
  },
  'instruments-and-equipment': {
    name: 'Инструменты и оборудование',
    slug: 'instruments-and-equipment',
    full_path: 'instruments-and-equipment',
    categories: [
      { name: 'Общего назначения', slug: '', full_path: '' },
      { name: 'Строительное', slug: '', full_path: '' },
      { name: 'Для авторемонта', slug: '', full_path: '' },
      { name: 'Промышленное и коммерческое', slug: '', full_path: '' },
    ],
  },
  appliances: {
    name: 'Бытовая техника',
    slug: 'appliances',
    full_path: 'appliances',
    categories: [
      { name: 'Холодильники и морозильники', slug: 'fridges', full_path: 'appliances/fridges' },
      { name: 'Плиты, духовые шкафы и варочные панели', slug: 'stoves-ovens', full_path: 'appliances/stoves-ovens' },
      { name: 'Стиральные машины', slug: 'washing-machines', full_path: 'appliances/washing-machines' },
      { name: 'Кондиционеры', slug: 'air-conditioners', full_path: 'appliances/air-conditioners' },
      { name: 'Водонагреватели', slug: 'water-heaters', full_path: 'appliances/water-heaters' },
      { name: '...', slug: '', full_path: '' },
    ],
  },
  furniture: {
    name: 'Мебель и интерьер',
    slug: 'furniture',
    full_path: 'furniture',
    categories: [
      { name: 'Диваны — ', slug: 'sofas', full_path: 'furniture/sofas' },
      { name: 'Кровати — ', slug: 'beds', full_path: 'furniture/beds' },
      { name: 'Матрасы', slug: 'mattresses', full_path: 'furniture/mattresses' },
      { name: 'Кухни', slug: 'kitchens', full_path: 'furniture/kitchens' },
      { name: 'Столы', slug: 'tables', full_path: 'furniture/tables' },
      { name: 'Стулья, табуретки, кресла', slug: 'chairs-armchairs', full_path: 'furniture/chairs-armchairs' },
      { name: 'Шкафы — ', slug: '', full_path: '' },
      { name: 'Комоды и тумбы', slug: 'chests-cabinets', full_path: 'furniture/chests-cabinets' },
      { name: 'Текстиль для дома', slug: 'home-textiles', full_path: 'furniture/home-textiles' },
      { name: 'Шторы и жалюзи', slug: 'curtains-blinds', full_path: 'furniture/curtains-blinds' },
      { name: '...', slug: '', full_path: '' },
    ],
  },
  'water-tech': {
    name: 'Водная техника',
    slug: 'water-tech',
    full_path: 'water-tech',
  },
  'sport-tourism-hunting': {
    name: 'Спорт, туризм, охота',
    slug: 'sport-tourism-hunting',
    full_path: 'sport-tourism-hunting',
  },
  'garden-country': {
    name: 'Товары для дачи, сада и огорда',
    slug: 'garden-country',
    full_path: 'garden-country',
  },
  'pet-supplies': {
    name: 'Товары для животных',
    slug: 'pet-supplies',
    full_path: 'pet-supplies',
  },
  'clothes-shoes-accessories': {
    name: 'Одежда, обувь. аксуссуары',
    slug: 'clothes-shoes-accessories',
    full_path: 'clothes-shoes-accessories',
    categories: [
      { name: 'Женская одежда — ', slug: 'womens-clothing', full_path: 'clothes-shoes-accessories/womens-clothing' },
      { name: 'Женская обувь', slug: 'womens-shoes', full_path: 'clothes-shoes-accessories/womens-shoes' },
      { name: 'Мужская одежда — ', slug: 'mens-clothing', full_path: 'clothes-shoes-accessories/mens-clothing' },
      { name: 'Мужская обувь', slug: 'mens-shoes', full_path: 'clothes-shoes-accessories/mens-shoes' },
      { name: 'Детская одежда — ', slug: 'kids-clothing', full_path: 'clothes-shoes-accessories/kids-clothing' },
      { name: 'Детская обувь', slug: 'kids-shoes', full_path: 'clothes-shoes-accessories/kids-shoes' },
      { name: '', slug: '', full_path: '' },
      { name: '', slug: '', full_path: '' },
      { name: 'Аксессуары и бижутерия', slug: 'accessories-jewelry', full_path: 'clothes-shoes-accessories/accessories-jewelry' },
      { name: 'Специодежда', slug: '', full_path: '' },
    ],
  },
  kitchenware: {
    name: 'Посуда и кухонные принадлежности',
    slug: 'kitchenware',
    full_path: 'kitchenware',
    categories: [
      { name: 'Посуда', slug: 'tableware', full_path: 'kitchenware/tableware' },
      { name: 'Столовые приборы', slug: 'cutlery', full_path: 'kitchenware/cutlery' },
      { name: 'Кухонный инвентарь и аксессуары', slug: 'kitchen-tools', full_path: 'kitchenware/kitchen-tools' },
    ],
  },
  'fabrics-haberdashery': {
    name: 'Ткани и швейная фурнитура',
    slug: 'fabrics-haberdashery',
    full_path: 'fabrics-haberdashery',
  },
  stationery: {
    name: 'Канцтовары',
    slug: 'stationery',
    full_path: 'stationery',
  },
  'food-beverages': {
    name: 'Продукты и напитки',
    slug: 'food-beverages',
    full_path: 'food-beverages',
  },
  'containers-packaging': {
    name: 'Тара и упаковка',
    slug: 'containers-packaging',
    full_path: 'containers-packaging',
  },
  beauty: {
    name: 'Красота',
    slug: 'beauty',
    full_path: 'beauty',
  },
  health: {
    name: 'Здоровье',
    slug: 'health',
    full_path: 'health',
  },
  'gifts-souvenirs-flowers': {
    name: 'Подарки, сувениры, цветы',
    slug: 'gifts-souvenirs-flowers',
    full_path: 'gifts-souvenirs-flowers',
  },
  'kids-maternity': {
    name: 'Товары для детей',
    slug: 'kids-maternity',
    full_path: 'kids-maternity',
    categories: [
      { name: 'Коляски и переноски', slug: '', full_path: '' },
      { name: 'Питание и кормление', slug: 'baby-feeding', full_path: 'kids-maternity/baby-feeding' },
      { name: 'Гигиена и уход', slug: 'baby-hygiene', full_path: 'kids-maternity/baby-hygiene' },
      { name: 'Игрушки и игры', slug: 'toys-games', full_path: 'kids-maternity/toys-games' },
      { name: 'Детские спортивные товары и активный отдых', slug: 'kids-sports', full_path: 'kids-maternity/kids-sports' },
      { name: 'Школа', slug: 'school-supplies', full_path: 'kids-maternity/school-supplies' },
    ],
  },
};
