export const mainCatalogDataFront = {
  'auto-moto': {
    name: 'Авто-мото',
    categories: [
      { name: 'Запчасти', slug: '', full_path: '' },
      { name: 'Шины — ', slug: '', full_path: '' },
      { name: 'Диски — ', slug: '', full_path: '' },
      { name: 'Колпаки', slug: '', full_path: '' },
      { name: 'Аккумуляторы', slug: '', full_path: '' },
      { name: 'Принадлежности', slug: '', full_path: '' },
      { name: 'Автохимия и ГСМ', slug: '', full_path: '' },
      { name: '...', slug: '', full_path: '' },
    ],
  },
  'computers-tech': {
    name: 'Компьютеры и цифровая техника',
    categories: [
      { name: 'Фото и видеокамеры', slug: '', full_path: '' },
      { name: 'Телефоны', slug: '', full_path: '' },
      { name: 'Умные часы и фитнес-браслеты', slug: '', full_path: '' },
      { name: 'Ноутбуки — ', slug: '', full_path: '' },
      { name: 'Планшеты', slug: '', full_path: '' },
      { name: 'Персональные компьютеры', slug: '', full_path: '' },
      { name: 'Периферия — ', slug: '', full_path: '' },
      { name: 'Комплектующие', slug: '', full_path: '' },
      { name: 'Игровые приставки и консоли', slug: '', full_path: '' },
      { name: '...', slug: '', full_path: '' },
    ],
  },
  construction: {
    name: 'Строительство, ремонт, материалы',
    categories: [
      { name: 'Сантехника — ', slug: '', full_path: '' },
      { name: 'Электрика', slug: '', full_path: '' },
      { name: 'Плитка / Кафель', slug: '', full_path: '' },
      { name: 'Двери — ', slug: '', full_path: '' },
      { name: 'Окна', slug: '', full_path: '' },
      { name: 'Пиломатериалы', slug: '', full_path: '' },
      { name: 'Древесные плиты', slug: '', full_path: '' },
      { name: 'Металлопрокат', slug: '', full_path: '' },
      { name: 'Цемент и строительные смеси', slug: '', full_path: '' },
      { name: 'Лакокрасочные материалы', slug: '', full_path: '' },
      { name: '...', slug: '', full_path: '' },
    ],
  },
  'instruments-and-equipment': {
    name: 'Инструменты и оборудование',
    categories: [
      { name: 'Общего назначения', slug: '', full_path: '' },
      { name: 'Строительное', slug: '', full_path: '' },
      { name: 'Для авторемонта', slug: '', full_path: '' },
      { name: 'Промышленное и коммерческое', slug: '', full_path: '' },
    ],
  },
  appliances: {
    name: 'Бытовая техника',
    categories: [
      { name: 'Холодильники и морозильники', slug: '', full_path: '' },
      { name: 'Плиты, духовые шкафы и варочные панели', slug: '', full_path: '' },
      { name: 'Стиральные машины', slug: '', full_path: '' },
      { name: 'Кондиционеры', slug: '', full_path: '' },
      { name: 'Водонагреватели', slug: '', full_path: '' },
      { name: '...', slug: '', full_path: '' },
    ],
  },
  furniture: {
    name: 'Мебель и интерьер',
    categories: [
      { name: 'Диваны — ', slug: '', full_path: '' },
      { name: 'Кровати — ', slug: '', full_path: '' },
      { name: 'Матрасы', slug: '', full_path: '' },
      { name: 'Кухни', slug: '', full_path: '' },
      { name: 'Столы', slug: '', full_path: '' },
      { name: 'Стулья, табуретки, кресла', slug: '', full_path: '' },
      { name: 'Шкафы — ', slug: '', full_path: '' },
      { name: 'Комоды и тумбы', slug: '', full_path: '' },
      { name: 'Текстиль для дома', slug: '', full_path: '' },
      { name: 'Шторы и жалюзи', slug: '', full_path: '' },
      { name: '...', slug: '', full_path: '' },
    ],
  },
  'water-tech': {
    name: 'Водная техника',
  },
};
