import auto1 from '../assets/images/1_auto.png';
import computers2 from '../assets/images/2_computers.png';
import construction3 from '../assets/images/3_construction.png';
import tools4 from '../assets/images/4_tools.png';
import household5 from '../assets/images/5_household.png';
import furniture6 from '../assets/images/6_furniture.png';
import waterGoods7 from '../assets/images/7_waterGoods.png';
import tourism8 from '../assets/images/8_tourism.png';
import dacha9 from '../assets/images/9_dacha.png';
import animals10 from '../assets/images/10_animals.png';
import clothes11 from '../assets/images/11_clothes.png';
import dishes12 from '../assets/images/12_dishes.png';
import fabrics13 from '../assets/images/13_fabrics.png';
import stationery14 from '../assets/images/14_stationery.png';
import foods15 from '../assets/images/15_foods.png';
import packaging16 from '../assets/images/16_packaging.png';
import beauty17 from '../assets/images/17_beauty.png';
import health18 from '../assets/images/18_health.png';
import souvenirs19 from '../assets/images/19_souvenirs.png';
import toys20 from '../assets/images/20_toys.png';

export const mainCatalogUiData = {
  'avto-moto': {
    area: 'auto',
    order: 1,
    src: auto1,
    alt: 'Авто',
    bgColor: 'headerBgFirstVar',
    headerTitleSize: '22px',
    leftMarginTitle: '38px',
    headerHeight: '72px',
    cardHeight: '312px',
    listPaddingLeft: '29px',
    listPaddingTop: '15px',
    listPaggingRight: '46px',
    listPaddindBottom: '52px',
  },
  'kompiutery-i-tsifrovaia-tekhnika': {
    area: 'computers',
    order: 2,
    src: computers2,
    alt: 'Компьютеры',
    bgColor: 'headerBgFirstVar',
    headerTitleSize: '18px',
    leftMarginTitle: '6px',
    headerHeight: '67px',
    cardHeight: '312px',
    listPaddingLeft: '21px',
    listPaddingTop: '16px', //или 25
    listPaddingRight: '17px',
    listPaddindBottom: '26px',
  },
  'stroitelstvo-remont-stroi-prom-materialy': {
    area: 'construction',
    order: 3,
    src: construction3,
    alt: 'Строительство',
    bgColor: 'headerBgFirstVar',
    headerTitleSize: '18px',
    leftMarginTitle: '15px',
    headerHeight: '67px',
    cardHeight: '315px',
    listPaddingLeft: '23px',
    listPaddingTop: '9px', //15
    listPaddingRight: '29px',
    listPaddindBottom: '12px',
  },
  'instrumenty-i-oborudovanie': {
    area: 'tools',
    order: 4,
    src: tools4,
    alt: 'Инструменты',
    bgColor: 'headerBgSecondVar',
    headerTitleSize: '18px',
    leftMarginTitle: '16px',
    headerHeight: '67px',
    cardHeight: '207px',
    listPaddingLeft: '21px',
    listPaddingTop: '16px',
    listPaddingRight: '12px',
    listPaddindBottom: '21px',
  },

  'bytovaia-tekhnika': {
    area: 'appliances',
    order: 5,
    src: household5,
    alt: 'Бытовая техника',
    bgColor: 'headerBgSecondVar',
    headerTitleSize: '18px',
    leftMarginTitle: '8px',
    headerHeight: '67px',
    cardHeight: '280px',
    listPaddingLeft: '21px',
    listPaddingTop: '16px',
    listPaddingRight: '23px',
    listPaddindBottom: '15px',
  },
  'mebel-i-interer': {
    area: 'furniture',
    order: 6,
    src: furniture6,
    alt: 'Мебель',
    bgColor: 'headerBgSecondVar',
    headerTitleSize: '18px',
    leftMarginTitle: '7px',
    headerHeight: '67px',
    cardHeight: '280px',
    listPaddingLeft: '12px',
    listPaddingTop: '8px',
    listPaddingRight: '28',
    listPaddindBottom: '1px',
  },
  'vodnaia-tekhnika': {
    area: 'water-tech',
    order: 7,
    src: waterGoods7,
    alt: 'Товары для воды',
    bgColor: 'headerBgSecondVar',
    headerTitleSize: '16px',
    leftMarginTitle: '37px',
    headerHeight: '60px',
    cardHeight: '60px',
  },
  'sport-turizm-okhota': {
    area: 'sport-tourism',
    order: 8,
    src: tourism8,
    alt: 'Туризм',
    bgColor: 'headerBgFirstVar',
    headerTitleSize: '16px',
    leftMarginTitle: '34px',
    headerHeight: '67px',
    cardHeight: '67px',
  },
  'tovary-dlia-dachi-sada-i-ogoroda': {
    area: 'garden-country',
    order: 9,
    src: dacha9,
    alt: 'Дача',
    bgColor: 'headerBgFirstVar',
    headerTitleSize: '16px',
    leftMarginTitle: '28px',
    headerHeight: '67px',
    cardHeight: '67px',
  },
  'tovary-dlia-zhivotnykh': {
    area: 'animals',
    order: 10,
    src: animals10,
    alt: 'Товары для животных',
    bgColor: 'headerBgFirstVar',
    headerTitleSize: '16px',
    leftMarginTitle: '34px',
    headerHeight: '67px',
    cardHeight: '67px',
  },
  'odezhda-obuv-i-aksessuary': {
    area: 'clothes',
    order: 11,
    src: clothes11,
    alt: 'Одежда',
    bgColor: 'headerBgFirstVar',
    headerTitleSize: '18px',
    leftMarginTitle: '13px',
    headerHeight: '67px',
    cardHeight: '265px',
    listPaddingLeft: '13px',
    listPaddingTop: '15px',
    listPaddingRight: '4px',
    listPaddindBottom: '26px',
  },
  'posuda-i-kukhonnye-prinadlezhnosti': {
    area: 'kitchenware',
    order: 12,
    src: dishes12,
    alt: 'Посуда',
    bgColor: 'headerBgFirstVar',
    headerTitleSize: '18px',
    leftMarginTitle: '10px',
    headerHeight: '67px',
    cardHeight: '172px',
    listPaddingLeft: '13px',
    listPaddingTop: '15px',
    listPaddingRight: '5px',
    listPaddindBottom: '25px',
  },
  'tkani-i-shveinaia-furnitura': {
    area: 'fabrics',
    order: 13,
    src: fabrics13,
    alt: 'Ткани',
    bgColor: 'headerBgFirstVar',
    headerTitleSize: '16px',
    leftMarginTitle: '11px',
    headerHeight: '67px',
    cardHeight: '67px',
  },
  'kantstovary-i-knigi': {
    area: 'stationery',
    order: 14,
    src: stationery14,
    alt: 'Канцелярия',
    bgColor: 'headerBgSecondVar ',
    headerTitleSize: '16px',
    leftMarginTitle: '47px',
    headerHeight: '67px',
    cardHeight: '67px',
  },
  'produkty-i-napitki': {
    area: 'food-beverages',
    order: 15,
    src: foods15,
    alt: 'Продукты питания',
    bgColor: 'headerBgSecondVar ',
    headerTitleSize: '18px',
    leftMarginTitle: '30px',
    headerHeight: '67px',
    cardHeight: '67px',
  },
  'tara-i-upakovka': {
    area: 'packaging',
    order: 16,
    src: packaging16,
    alt: 'Упаковка',
    bgColor: 'headerBgSecondVar ',
    headerTitleSize: '16px',
    leftMarginTitle: '21px',
    headerHeight: '67px',
    cardHeight: '67px',
  },
  krasota: {
    area: 'beauty',
    order: 17,
    src: beauty17,
    alt: 'Красота',
    bgColor: 'headerBgSecondVar ',
    headerTitleSize: '16px',
    leftMarginTitle: '57px',
    headerHeight: '67px',
    cardHeight: '67px',
  },
  zdorove: {
    area: 'health',
    order: 18,
    src: health18,
    alt: 'Здоровье',
    bgColor: 'headerBgSecondVar ',
    headerTitleSize: '18px',
    leftMarginTitle: '43px',
    headerHeight: '67px',
    cardHeight: '67px',
  },
  'podarki-suveniry-tsvety': {
    area: 'gifts',
    order: 19,
    src: souvenirs19,
    alt: 'Сувениры',
    bgColor: 'headerBgSecondVar ',
    headerTitleSize: '16px',
    leftMarginTitle: '32px',
    headerHeight: '67px',
    cardHeight: '67px',
  },
  'deti-i-materinstvo': {
    area: 'kids',
    order: 20,
    src: toys20,
    alt: 'Игрушки',
    bgColor: 'headerBgSecondVar ',
    headerTitleSize: '18px',
    leftMarginTitle: '36px',
    headerHeight: '67px',
    cardHeight: '269px',
    listPaddingLeft: '26px',
    listPaddingTop: '13px',
    listPaddingRight: '55px',
    listPaddindBottom: '10px',
  },
} as const;
