const CATALOG_RU_NAMES: Record<string, string> = {
  'avto-moto': 'Авто-мото',
  'vodnaia-tekhnika': 'Водная техника',
  'kompiutery-i-tsifrovaia-tekhnika': 'Компьютеры и цифровая техника',
  'bytovaia-tekhnika': 'Бытовая техника',
  'stroitelstvo-remont-stroi-prom-materialy': 'Строительство и ремонт',
  'mebel-i-interer': 'Мебель и интерьер',
  'posuda-i-kukhonnye-prinadlezhnosti': 'Посуда и кухонные принадлежности',
  'odezhda-obuv-i-aksessuary': 'Одежда, обувь и аксессуары',
  'tkani-i-shveinaia-furnitura': 'Ткани и швейная фурнитура',
  'kantstovary-i-knigi': 'Канцтовары',
  'tara-i-upakovka': 'Тара и упаковка',
  'tovary-dlia-dachi-sada-i-ogoroda': 'Товары для дачи, сада и огорода',
  'tovary-dlia-zhivotnykh': 'Товары для животных',
  'produkty-i-napitki': 'Продукты и напитки',
  krasota: 'Красота',
  zdorove: 'Здоровье',
  'deti-i-materinstvo': 'Товары для детей',
  'instrumenty-i-oborudovanie': 'Инструменты и оборудование',
  'sport-turizm-okhota': 'Спорт, туризм, охота',
  'podarki-suveniry-tsvety': 'Подарки, сувениры, цветы',
};
